/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import models.Connection;
import java.sql.*;
import java.text.SimpleDateFormat;
import models.Fakultas;
import models.Prodi;
import java.util.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.MahasiswaBaru;
import models.PendidikanAkhir;

/**
 *
 * @author annis
 */
public class menuUtama extends javax.swing.JFrame {

    /**
     * Creates new form menuUtama
     */
    List<Fakultas> fakultas = new ArrayList<>();
    List<Prodi> prodi = new ArrayList<>();
    private boolean isUpdatingProdi = false;
    List<MahasiswaBaru> mhs = new ArrayList<>();
    List<PendidikanAkhir> pendidikan = new ArrayList<>();
    public menuUtama() {
        initComponents(); 
        showComboBoxFak();
        cmbProdi.setEnabled(false);
        showComboBoxSekolah();
        showComboBoxJurusanSklh();
        showComboBoxNama();
        showTableData();
        showTableDataPend();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        form = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pend = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jp1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNisn = new javax.swing.JTextField();
        txtKota = new javax.swing.JTextField();
        cmbFak = new javax.swing.JComboBox<>();
        cmbProdi = new javax.swing.JComboBox<>();
        jjk = new javax.swing.JLabel();
        rdbLaki = new javax.swing.JRadioButton();
        rdbPr = new javax.swing.JRadioButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKosongkan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jkalender = new com.toedter.calendar.JDateChooser();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblmhsbaru = new javax.swing.JTable();
        txtID = new javax.swing.JLabel();
        btnExit1 = new javax.swing.JLabel();
        jp2 = new javax.swing.JPanel();
        btnExitPend = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtSKHUN = new javax.swing.JTextField();
        txtNsklh = new javax.swing.JTextField();
        txtKsklh = new javax.swing.JTextField();
        txtPsklh = new javax.swing.JTextField();
        btnSimpanPend = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPend = new javax.swing.JTable();
        btnEditPend = new javax.swing.JButton();
        btnKosongPend = new javax.swing.JButton();
        cmbSklh = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cmbJsklh = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        cmbNama = new javax.swing.JComboBox<>();
        txtidPend = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        form.setBackground(new java.awt.Color(204, 204, 255));
        form.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel1.setText("Informasi Pribadi");

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        pend.setBackground(new java.awt.Color(204, 204, 255));
        pend.setPreferredSize(new java.awt.Dimension(181, 40));
        pend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel2.setText("Pendidikan Terakhir");

        javax.swing.GroupLayout pendLayout = new javax.swing.GroupLayout(pend);
        pend.setLayout(pendLayout);
        pendLayout.setHorizontalGroup(
            pendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pendLayout.setVerticalGroup(
            pendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel3.setText("Pendaftaran Mahasiswa Baru");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pend, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        jp1.setBackground(new java.awt.Color(212, 175, 55));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel4.setText("Nama Lengkap");

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel5.setText("NISN");
        jLabel5.setPreferredSize(new java.awt.Dimension(80, 16));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel6.setText("Tanggal Lahir");
        jLabel6.setPreferredSize(new java.awt.Dimension(80, 16));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel7.setText("Kota");
        jLabel7.setPreferredSize(new java.awt.Dimension(80, 16));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel8.setText("Alamat");
        jLabel8.setPreferredSize(new java.awt.Dimension(80, 16));

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel9.setText("Fakultas ");
        jLabel9.setPreferredSize(new java.awt.Dimension(80, 16));

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel10.setText("Program Studi");
        jLabel10.setPreferredSize(new java.awt.Dimension(80, 16));

        txtNama.setToolTipText("Isikan Nama Anda");

        txtNisn.setToolTipText("Isikan NISN Anda");

        txtKota.setToolTipText("Isikan Kota Lahir Anda");

        cmbFak.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        cmbFak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbProdi.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        cmbProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jjk.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jjk.setText("Jenis Kelamin");
        jjk.setPreferredSize(new java.awt.Dimension(80, 16));

        rdbLaki.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        rdbLaki.setText("Laki-laki");
        rdbLaki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbLakiMouseClicked(evt);
            }
        });

        rdbPr.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        rdbPr.setText("Perempuan");
        rdbPr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbPrMouseClicked(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKosongkan.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnKosongkan.setText("Kosongkan");
        btnKosongkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosongkanActionPerformed(evt);
            }
        });

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        tblmhsbaru.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        tblmhsbaru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblmhsbaru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmhsbaruMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblmhsbaru);

        btnExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Emergency Exit.png"))); // NOI18N
        btnExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExit1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jjk, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtKota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                                .addComponent(txtNisn, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbFak, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp1Layout.createSequentialGroup()
                                .addComponent(rdbLaki, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdbPr, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jkalender, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 267, Short.MAX_VALUE)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnKosongkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29))
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(223, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btnExit1))
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNisn)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jjk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdbLaki)
                            .addComponent(rdbPr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(jkalender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbFak, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnExit1))
                        .addGap(38, 38, 38)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKosongkan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jp1);

        jp2.setBackground(new java.awt.Color(0, 43, 91));
        jp2.setPreferredSize(new java.awt.Dimension(857, 675));

        btnExitPend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Emergency Exit.png"))); // NOI18N
        btnExitPend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitPendMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PENDIDIKAN AKHIR");

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nama Sekolah");

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Jurusan");

        jLabel14.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Kota");

        jLabel15.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Provinsi");

        jLabel16.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nilai SKHUN");

        txtNsklh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNsklhActionPerformed(evt);
            }
        });

        txtKsklh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKsklhActionPerformed(evt);
            }
        });

        txtPsklh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPsklhActionPerformed(evt);
            }
        });

        btnSimpanPend.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnSimpanPend.setText("Simpan");
        btnSimpanPend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPendActionPerformed(evt);
            }
        });

        tblPend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPendMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPend);

        btnEditPend.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnEditPend.setText("Edit");
        btnEditPend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPendActionPerformed(evt);
            }
        });

        btnKosongPend.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnKosongPend.setText("Kosongkan");

        cmbSklh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSklh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSklhActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Sekolah");

        cmbJsklh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel18.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nama");

        cmbNama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Go Back.png"))); // NOI18N

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(66, 66, 66)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel18))
                                .addGap(25, 25, 25)
                                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSKHUN, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jp2Layout.createSequentialGroup()
                                        .addComponent(btnSimpanPend)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEditPend)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnKosongPend))
                                    .addComponent(txtPsklh, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cmbJsklh, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtKsklh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jp2Layout.createSequentialGroup()
                                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cmbSklh, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbNama, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNsklh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtidPend, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(446, Short.MAX_VALUE))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExitPend))))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11))
                    .addComponent(btnExitPend)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtidPend, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbNama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSklh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNsklh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbJsklh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKsklh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPsklh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSKHUN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(43, 43, 43)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanPend)
                    .addComponent(btnEditPend)
                    .addComponent(btnKosongPend))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jp2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        jp1.setVisible(true);
        jp2.setVisible(false);
        
        form.setBackground(Color.white);
        pend.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_formMouseClicked

    private void pendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendMouseClicked
        // TODO add your handling code here:
        jp2.setVisible(true);
        jp1.setVisible(false);
        
        pend.setBackground(Color.white);
        form.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_pendMouseClicked

    public void showComboBoxFak(){
        Connection.koneksi();
        String sql = "SELECT * FROM fakultas";
        try{
            fakultas.clear();
            Connection.rs = Connection.stmt.executeQuery(sql);
            while(Connection.rs.next()){
                fakultas.add(new Fakultas(Connection.rs.getInt("id_fakultas"), Connection.rs.getString("nama_fakultas")));
           }
            cmbFak.setModel(new DefaultComboBoxModel(fakultas.toArray()));
            cmbFak.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e){
                    if(!isUpdatingProdi){
                    cmbProdi.setEnabled(true);
                    Fakultas fklts = (Fakultas)cmbFak.getSelectedItem();
                    showComboBoxProdi(fklts.getId_fakultas());
                    }
                }
            });
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    public void showComboBoxProdi(int id){
        Connection.koneksi();
        String sql = "SELECT * FROM prodi where id_fakultas="+id;
        try{
            isUpdatingProdi = true;
            prodi.clear();
            Connection.rs = Connection.stmt.executeQuery(sql);
            while(Connection.rs.next()){
                prodi.add(new Prodi(Connection.rs.getInt("id_prodi"), Connection.rs.getString("nama_prodi"), Connection.rs.getInt("id_fakultas")));
            }
            cmbProdi.setModel(new DefaultComboBoxModel(prodi.toArray()));
            isUpdatingProdi = false;
        }catch(Exception e){
            e.printStackTrace();
            isUpdatingProdi = false;
        }
    }
    
    public void showComboBoxSekolah(){
        cmbSklh.removeAllItems();
        cmbSklh.addItem("SMA");
        cmbSklh.addItem("SMK");
        cmbSklh.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e){
                    showComboBoxJurusanSklh();
                }
            });
    }
    
    public void showComboBoxJurusanSklh(){
        String pilihsklh = (String) cmbSklh.getSelectedItem();
        cmbJsklh.removeAllItems();
        
        if("SMA".equals(pilihsklh)){
            cmbJsklh.addItem("IPA");
            cmbJsklh.addItem("IPS");
        }else if("SMK".equals(pilihsklh)){
            cmbJsklh.addItem("Teknik Komputer Jaringan");
            cmbJsklh.addItem("Teknik Bisnis Sepeda Motor");
            cmbJsklh.addItem("Teknik Audio Video");
            cmbJsklh.addItem("Rekayasa Perangkat Lunak");
            cmbJsklh.addItem("Teknik Otomotif");
            cmbJsklh.addItem("Akuntansi");
            cmbJsklh.addItem("Perhotelan");
            cmbJsklh.addItem("Tata Boga");
            cmbJsklh.addItem("Tata Rias dan Kecantikan");
        }
    }
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String jkel="";
        String nama = txtNama.getText();
        int nisn = Integer.parseInt(txtNisn.getText());
        String kota = txtKota.getText();
        String alamat = txtAlamat.getText();
        Fakultas f = (Fakultas)cmbFak.getSelectedItem();
        Prodi p = (Prodi)cmbProdi.getSelectedItem();
        int id = Integer.parseInt(txtID.getText());
        
        Connection.koneksi();
        String sql = "UPDATE mhs_baru SET id_fakultas=?, id_prodi=?, nisn=?, nama=?, jk=?, tgl_lahir=?, kota=?, alamat=? WHERE id_pendaftaran=?";
        try{
            PreparedStatement ps = Connection.conn.prepareStatement(sql);
            ps.setString(4, nama);
            ps.setInt(3, nisn);
            if(rdbLaki.isSelected() == true)jkel="Laki-laki";
                else
                    if(rdbPr.isSelected()== true)jkel="Perempuan";
            ps.setString(5, jkel);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = sdf.format(jkalender.getDate());
            ps.setString(6, tanggal);
            ps.setString(7, kota);
            ps.setString(8, alamat);
            ps.setInt(1, f.getId_fakultas());
            ps.setInt(2, p.getId_prodi());
            ps.setInt(9, id);
            
            ps.execute();
            Connection.stmt.close();
            kosongkan();
            showTableData();
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtID.getText());
        
        String sql = "delete from mhs_baru where id_pendaftaran = "+id;
        Connection.koneksi();
        try{
            PreparedStatement ps = Connection.conn.prepareStatement(sql);
            ps.execute();
            Connection.stmt.close();
            Connection.conn.close();
            kosongkan();
            showTableData();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKosongkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongkanActionPerformed
        // TODO add your handling code here:
        kosongkan();
        
    }//GEN-LAST:event_btnKosongkanActionPerformed
    
    private void kosongkan(){
        txtNama.setText("");
        txtNisn.setText("");
        rdbLaki.setSelected(false);
        rdbPr.setSelected(false);
        jkalender.setDate(null);
        txtKota.setText("");
        txtAlamat.setText("");
        cmbProdi.setEnabled(false);
        showComboBoxFak();
    }

    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String jkel="";
        String nama = txtNama.getText();
        int nisn = Integer.parseInt(txtNisn.getText());
        String kota = txtKota.getText();
        String alamat = txtAlamat.getText();
        Fakultas f = (Fakultas)cmbFak.getSelectedItem();
        Prodi p = (Prodi)cmbProdi.getSelectedItem();
        
        Connection.koneksi();
        String sql = "INSERT INTO mhs_baru(id_fakultas, id_prodi, nisn, nama, jk, tgl_lahir, kota, alamat) VALUES (?,?,?,?,?,?,?,?)";
        try{
            PreparedStatement ps = Connection.conn.prepareStatement(sql);
            ps.setString(4, nama);
            ps.setInt(3, nisn);
            if(rdbLaki.isSelected() == true){
                jkel="Laki-laki";
            }
            if(rdbPr.isSelected()== true){
                jkel="Perempuan";
            }
            ps.setString(5, jkel);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = sdf.format(jkalender.getDate());
            ps.setString(6, tanggal);
            ps.setString(7, kota);
            ps.setString(8, alamat);
            ps.setInt(1, f.getId_fakultas());
            ps.setInt(2, p.getId_prodi());
            
            ps.execute();
            Connection.stmt.close();
            kosongkan();
            showTableData();
        }catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    public void showTableData()
    {
        Connection.koneksi();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Fakultas");
        model.addColumn("Program Studi");
        model.addColumn("NISN");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Tanggal Lahir");
        model.addColumn("Kota");
        model.addColumn("Alamat");
        String sql = "SELECT * FROM mhs_baru mb JOIN fakultas f ON mb.id_fakultas = f.id_fakultas JOIN prodi p on mb.id_prodi = p.id_prodi";
        try{
            mhs.clear();
            Connection.rs = Connection.stmt.executeQuery(sql);
            while(Connection.rs.next())
            {
                mhs.add(new MahasiswaBaru(Connection.rs.getInt("id_pendaftaran"), Connection.rs.getInt("id_fakultas"), 
                Connection.rs.getInt("id_prodi"), Connection.rs.getInt("nisn"), Connection.rs.getString("nama"), 
                        Connection.rs.getString("jk"), Connection.rs.getDate("tgl_lahir"), Connection.rs.getString("kota"), Connection.rs.getString("alamat")));
            }
            
           int i = 1;
           for(MahasiswaBaru b: mhs)
           {
               int idf = b.getId_fakultas();
               String namaFakultas = getDataFakultas(fakultas, idf);
               int idp = b.getId_prodi();
               String namaProdi = getDataProdi(prodi, idp);
               model.addRow(new Object[] {
                   i,namaFakultas, namaProdi, b.getNisn(), b.getNama(), b.getJk(), b.getTgl_lahir(), b.getKota(), b.getAlamat()
               });
               i++;
           }
           Connection.rs.close();
           tblmhsbaru.setModel(model);
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    public String getDataFakultas(List<Fakultas> f, int id){
        for (Fakultas _f : f){
            if(_f.getId_fakultas() == id){
                return _f.getNamaFakultas();
            }
        }
        return "-";
    }
    
    public int getFakIndex(List<Fakultas> authors, int id)
    {
        int targetIndex = -1;
        
        for(int i = 0; i < authors.size(); i++)
        {
            if(authors.get(i).getId_fakultas() == id)
            {
                targetIndex = i;
                break;
            }
        }
        
       return targetIndex;
    }
    
    public String getDataProdi(List<Prodi> p, int id){
        for (Prodi _p : p){
            if(_p.getId_prodi()== id){
                return _p.getNama_prodi();
            }
        }
        return "-";
    }
    
    public int getProdiIndex(List<Prodi> authors, int id)
    {
        int targetIndex = -1;
        
        for(int i = 0; i < authors.size(); i++)
        {
            if(authors.get(i).getId_prodi() == id)
            {
                targetIndex = i;
                break;
            }
        }
        
       return targetIndex;
    }
    
    public void getData(){
        int baris = tblmhsbaru.getSelectedRow();
        txtID.setVisible(false);
        txtID.setText(Integer.toString(mhs.get(baris).getId_pendaftaran()));
        txtNama.setText(mhs.get(baris).getNama());
        txtNisn.setText(Integer.toString(mhs.get(baris).getNisn()));
        jkalender.setDate(mhs.get(baris).getTgl_lahir());
        txtKota.setText(mhs.get(baris).getKota());
        txtAlamat.setText(mhs.get(baris).getAlamat());
        cmbFak.setSelectedIndex(getFakIndex(fakultas, mhs.get(baris).getId_fakultas()));
        cmbProdi.setSelectedIndex(getProdiIndex(prodi, mhs.get(baris).getId_prodi()));
        if(rdbLaki.getText().equals(mhs.get(baris).getJk())){
            rdbLaki.setSelected(true);
            rdbPr.setSelected(false);
        }
        if(rdbPr.getText().equals(mhs.get(baris).getJk())){
            rdbPr.setSelected(true);
            rdbLaki.setSelected(false);
        }
    }
    private void btnEditPendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPendActionPerformed
        // TODO add your handling code here:
        // nama, sekolahcmb, namasekolah, cmbjurusan, kota, provinsi, nilaiskhun
        String pilihsklh = (String) cmbSklh.getSelectedItem();
        String namasekolah = txtNsklh.getText();
        String pilihJ = (String) cmbJsklh.getSelectedItem();
        String kota = txtKsklh.getText();
        String provinsi = txtPsklh.getText();
        double nilaiskhun = Double.parseDouble(txtSKHUN.getText());
        int id = Integer.parseInt(txtidPend.getText());
        
        Connection.koneksi();
        String sql = "UPDATE pendidikan_akhir SET sekolah=?, nama_sekolah=?, jurusan=?, kota=?, provinsi=?, nilai_skhun=? WHERE id_pendidikan=?";
        try{
            PreparedStatement ps = Connection.conn.prepareStatement(sql);
            ps.setString(1, pilihsklh);
            ps.setString(2, namasekolah);
            ps.setString(3, pilihJ);
            ps.setString(4, kota);
            ps.setString(5, provinsi);
            ps.setDouble(6, nilaiskhun);
            ps.setInt(7, id);
            
            ps.execute();
            Connection.stmt.close();
           //kosongkan();
            showTableDataPend();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditPendActionPerformed
    public void getDataPend(){
        int baris = tblPend.getSelectedRow();
        txtidPend.setVisible(false);
        txtidPend.setText(Integer.toString(pendidikan.get(baris).getId_pendidikan()));
        cmbNama.setSelectedIndex(getPenIndex(mhs, pendidikan.get(baris).getId_pendaftaran()));
        cmbSklh.setSelectedItem(pendidikan.get(baris).getSekolah());
        txtNsklh.setText(pendidikan.get(baris).getNama_Sekolah());
        showComboBoxJurusanSklh();
        cmbJsklh.setSelectedItem(pendidikan.get(baris).getJurusan());
        txtKsklh.setText(pendidikan.get(baris).getKota_Sekolah());
        txtPsklh.setText(pendidikan.get(baris).getProvinsi());
        txtSKHUN.setText(Double.toString(pendidikan.get(baris).getNilai_skhun()));
    }
    
    public int getPenIndex(List<MahasiswaBaru> authors, int id)
    {
        int targetIndex = -1;
        
        for(int i = 0; i < authors.size(); i++)
        {
            if(authors.get(i).getId_pendaftaran()== id)
            {
                targetIndex = i;
                break;
            }
        }
        
       return targetIndex;
    }
    private void txtNsklhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNsklhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNsklhActionPerformed

    private void txtKsklhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKsklhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKsklhActionPerformed

    private void txtPsklhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPsklhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPsklhActionPerformed

    public void showComboBoxNama(){
        Connection.koneksi();
        String sql = "SELECT * FROM mhs_baru";
        try{
            mhs.clear();
            Connection.rs = Connection.stmt.executeQuery(sql);
            while(Connection.rs.next()){
                mhs.add(new MahasiswaBaru(Connection.rs.getInt("id_pendaftaran"), Connection.rs.getInt("id_fakultas"), Connection.rs.getInt("id_prodi"), Connection.rs.getInt("nisn"), Connection.rs.getString("nama"), Connection.rs.getString("jk"), Connection.rs.getDate("tgl_lahir"), Connection.rs.getString("kota"), Connection.rs.getString("alamat")));
           }
            cmbNama.setModel(new DefaultComboBoxModel(mhs.toArray()));
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    private void btnSimpanPendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPendActionPerformed
        // TODO add your handling code here:
        MahasiswaBaru idPendaf = (MahasiswaBaru)cmbNama.getSelectedItem();
        String pilihsklh = (String) cmbSklh.getSelectedItem();
        String namasklh = txtNsklh.getText();
        String jurusan = (String) cmbJsklh.getSelectedItem();
        String kota = txtKsklh.getText();
        String provinsi = txtPsklh.getText();
        double nilaiSKHUN;
        
        Connection.koneksi();
        String sql = "INSERT INTO pendidikan_akhir(id_pendaftaran, sekolah, nama_sekolah, jurusan, kota, provinsi, nilai_skhun) VALUES "+"(?,?,?,?,?,?,?)";
        try{
            nilaiSKHUN = Double.parseDouble(txtSKHUN.getText());
            PreparedStatement ps = Connection.conn.prepareStatement(sql);
            ps.setInt(1, idPendaf.getId_pendaftaran());
            ps.setString(2, pilihsklh);
            ps.setString(3, namasklh);
            ps.setString(4, jurusan);
            ps.setString(5, kota);
            ps.setString(6, provinsi);
            ps.setDouble(7, nilaiSKHUN);
            
            ps.execute();
            Connection.stmt.close();
            showTableDataPend();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSimpanPendActionPerformed

    public void showTableDataPend()
    {
        Connection.koneksi();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Nama");
        model.addColumn("Sekolah");
        model.addColumn("Nama Sekolah");
        model.addColumn("Jurusan");
        model.addColumn("Kota");
        model.addColumn("Provinsi");
        model.addColumn("nilai_skhun");
        String sql = "SELECT * FROM pendidikan_akhir a JOIN mhs_baru b ON a.id_pendaftaran = b.id_pendaftaran";
        try{
            pendidikan.clear();
            Connection.rs = Connection.stmt.executeQuery(sql);
            while(Connection.rs.next())
            {
                pendidikan.add(new PendidikanAkhir(Connection.rs.getInt("id_pendaftaran"), Connection.rs.getInt("id_pendidikan"), Connection.rs.getString("sekolah"), 
                Connection.rs.getString("nama_sekolah"), Connection.rs.getString("jurusan"), Connection.rs.getString("kota"), Connection.rs.getString("Provinsi"), Connection.rs.getDouble("nilai_skhun")));
            }
            
           int i = 1;
           for(PendidikanAkhir b: pendidikan)
           {
               int idPend = b.getId_pendaftaran();
               String namaMhs = getDataMhs_baru(mhs, idPend);
               model.addRow(new Object[] {
                   i,namaMhs, b.getSekolah(), b.getNama_Sekolah(), b.getJurusan(), b.getKota_Sekolah(), b.getProvinsi(), b.getNilai_skhun()
               });
               i++;
           }
           Connection.rs.close();
           tblPend.setModel(model);
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private String getDataMhs_baru(List<MahasiswaBaru> mhs, int id){
        for (MahasiswaBaru _mhs : mhs){
            if(_mhs.getId_pendaftaran()== id){
                return _mhs.getNama();
            }
        }
        return "-";
    }
    
    private void tblmhsbaruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmhsbaruMouseClicked
        // TODO add your handling code here:
        getData();
    }//GEN-LAST:event_tblmhsbaruMouseClicked

    private void rdbLakiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbLakiMouseClicked
        // TODO add your handling code here:
        rdbPr.setSelected(false);
    }//GEN-LAST:event_rdbLakiMouseClicked

    private void rdbPrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbPrMouseClicked
        // TODO add your handling code here:
        rdbLaki.setSelected(false);
    }//GEN-LAST:event_rdbPrMouseClicked

    private void cmbSklhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSklhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSklhActionPerformed

    private void tblPendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPendMouseClicked
        // TODO add your handling code here:
        getDataPend();
    }//GEN-LAST:event_tblPendMouseClicked

    private void btnExitPendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitPendMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitPendMouseClicked

    private void btnExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExit1MouseClicked

    int xx, xy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditPend;
    private javax.swing.JLabel btnExit1;
    private javax.swing.JLabel btnExitPend;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKosongPend;
    private javax.swing.JButton btnKosongkan;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSimpanPend;
    private javax.swing.JComboBox<String> cmbFak;
    private javax.swing.JComboBox<String> cmbJsklh;
    private javax.swing.JComboBox<String> cmbNama;
    private javax.swing.JComboBox<String> cmbProdi;
    private javax.swing.JComboBox<String> cmbSklh;
    private javax.swing.JPanel form;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jjk;
    private com.toedter.calendar.JDateChooser jkalender;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel pend;
    private javax.swing.JRadioButton rdbLaki;
    private javax.swing.JRadioButton rdbPr;
    private javax.swing.JTable tblPend;
    private javax.swing.JTable tblmhsbaru;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JLabel txtID;
    private javax.swing.JTextField txtKota;
    private javax.swing.JTextField txtKsklh;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNisn;
    private javax.swing.JTextField txtNsklh;
    private javax.swing.JTextField txtPsklh;
    private javax.swing.JTextField txtSKHUN;
    private javax.swing.JLabel txtidPend;
    // End of variables declaration//GEN-END:variables
}
